"""empty message

Revision ID: 9bf9fe366955
Revises: e12805a37b37
Create Date: 2022-04-11 15:27:14.787075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf9fe366955'
down_revision = 'e12805a37b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phone', schema=None) as batch_op:
        batch_op.drop_column('image_url')


    # ### end Alembic commands ###
